# Group definitions
- name: Install dnsmasq
  package:
          name: "dnsmasq"
          state: present
- name: Setup dnsmasq global configuration
  template:
    src: dnsmasq.global.conf.j2
    dest: /etc/dnsmasq.d/global.conf
  notify: dnsmasq reload
- name: Setup dnsmasq interface specific configuration
  template: 
    src: dnsmasq.dhcp.conf.j2
    dest: /etc/dnsmasq.d/interface.conf
  when: (dnsmasq_dhcpenable is sameas true and dnsmasq_dhcp4ifs is defined) or (dnsmasq_dhcpenable is sameas true and dnsmasq_ipv6mode is defined)
- name: Enable and start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes
