- name: Install nftables
  apk:
          name: nftables
          state: present
- name: Install default rules and variables firewall mode
  template:
          src: firewall.nft.j2
          dest: /etc/nftables.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "firewall"
  notify: reload nftables alpine
- name: Install default rules and variables workstation mode
  template:
          src: workstation.nft.j2
          dest: /etc/nftables.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "workstation"
  notify: reload nftables alpine
- name: Install default rules and variables server mode
  template:
          src: server.nft.j2
          dest: /etc/nftables.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "server"
  notify: reload nftables alpine
- name: Enable nftables
  service:
          name: nftables
          state: started
          enabled: yes
