- name: Remove iptables
  apt:
          name: iptables
          state: absent
- name: Remove ufw
  apt:
          name: ufw
          state: absent
- name: Install nftables
  apt:
          name: nftables
          state: present
- name: Install nftables rules server mode
  template:
          src: server.nft.j2
          dest: /etc/nftables.conf
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "server"
  notify: reload nftables debian
- name: Install nftables rules workstation mode
  template:
          src: workstation.nft.j2
          dest: /etc/nftables.conf
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "workstation"
  notify: reload nftables debian
- name: Install nftables rules firewall mode
  template:
          src: firewall.nft.j2
          dest: /etc/nftables.conf
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "firewall"
  notify: reload nftables debian
- name: Enable nftables
  service:
          name: nftables
          state: started
          enabled: yes
