---
- name: Install rules for firewall mode
  template:
    src: "{{ templatename_rules_firewall }}"
    dest: "{{ filepath_nftablesrules }}"
    owner: "{{ ownername_nftablesrules }}"
    group: "{{ groupname_nftablesrules }}"
    mode: 0640
  when: nftablesmode == "firewall"
  notify: reload nftables
- name: Install rules for workstation mode
  template:
    src: "{{ templatename_rules_workstation }}"
    dest: "{{ filepath_nftablesrules }}"
    owner: "{{ ownername_nftablesrules }}"
    group: "{{ groupname_nftablesrules }}"
    mode: 0640
  when: nftablesmode == "workstation"
  notify: reload nftables
- name: "Install rules for server mode"
  template:
    src: "{{ templatename_rules_server }}"
    dest: "{{ filepath_nftablesrules }}"
    owner: "{{ ownername_nftablesrules }}"
    group: "{{ groupname_nftablesrules }}"
    mode: 0640
  when: nftablesmode == "server"
  notify: reload nftables
