- name: Remove iptables
  package:
          name: iptables
          state: absent
- name: Remove firewalld
  package:
          name: firewalld
          state: absent
- name: Install nftables
  package:
          name: nftables
          state: present
- name: enable nftables main include
  template:
    src: redhatsysconfignftables.j2
    dest: /etc/sysconfig/nftables.conf
- name: Install nftables rules server mode
  template:
          src: server.nft.j2
          dest: /etc/nftables/main.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "server"
  notify: reload nftables redhat
- name: Install nftables rules workstation mode
  template:
          src: workstation.nft.j2
          dest: /etc/nftables/main.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "workstation"
  notify: reload nftables redhat
- name: Install nftables rules firewall mode
  template:
          src: firewall.nft.j2
          dest: /etc/nftables/main.nft
          owner: root
          group: root
          mode: 0640
  when: nftablesmode == "firewall"
  notify: reload nftables redhat
- name: Enable nftables
  service:
          name: nftables
          state: started
          enabled: yes
