---
# handlers file for ansible_dnsmasq/
- name: dnsmasq reload
  service:
    name: "{{ servicename_dnsmasq }}"
    state: reloaded
- name: dnsmasq restart
  service:
    name: "{{ servicename_dnsmasq }}"
    state: restarted
